import { Product } from '@/context/CartContext';

export const products: Product[] = [
  {
    id: 'cnm001',
    slug: 'cnm013-vida-de-cowboy',
    sku: 'CNM013',
    name: 'Vida de Cowboy',
    price: 129.90,
    image: '/images/bone-01.jpg',
    color: 'Cáqui',
    category: 'bones',
    stock: 38,
  },
  {
    id: 'cnm002',
    slug: 'cnm018',
    sku: 'CNM018',
    name: 'CNM018',
    price: 139.90,
    image: '/images/bone-02.jpg',
    color: 'Preto',
    category: 'bones',
    stock: 33,
  },
  {
    id: 'cnm003',
    slug: 'cnm017',
    sku: 'CNM017',
    name: 'CNM017',
    price: 139.90,
    image: '/images/bone-03.jpg',
    color: 'Verde',
    category: 'bones',
    stock: 36,
  },
  {
    id: 'cnm004',
    slug: 'cnm015-laco-comprido',
    sku: 'CNM015',
    name: 'Laço Comprido',
    price: 129.90,
    image: '/images/bone-04.jpg',
    color: 'Marrom',
    category: 'bones',
    stock: 39,
  },
  {
    id: 'cnm005',
    slug: 'cnm014-vida-de-cowboy',
    sku: 'CNM014',
    name: 'Vida de Cowboy II',
    price: 129.90,
    image: '/images/bone-05.jpg',
    color: 'Areia',
    category: 'bones',
    stock: 40,
  },
  {
    id: 'cnm006',
    slug: 'cnm016-black-on',
    sku: 'CNM016',
    name: 'Black On',
    price: 129.90,
    image: '/images/bone-06.jpg',
    color: 'Preto',
    category: 'bones',
    stock: 44,
  },
  {
    id: 'cnm007',
    slug: 'cnm01-bone-boiadeiro',
    sku: 'CNM01',
    name: 'Boiadeiro',
    price: 149.90,
    image: '/images/bone-07.jpg',
    color: 'Palha',
    category: 'bones',
    stock: 3,
  },
  {
    id: 'cnm008',
    slug: 'cnm04-the-black',
    sku: 'CNM04',
    name: 'The Black',
    price: 149.90,
    image: '/images/bone-08.jpg',
    color: 'Preto Total',
    category: 'bones',
    stock: 1,
  },
  {
    id: 'cnm009',
    slug: 'cnm05-cacador',
    sku: 'CNM05',
    name: 'Caçador',
    price: 129.90,
    image: '/images/bone-09.jpg',
    color: 'Camuflado',
    category: 'bones',
    stock: 7,
  },
  {
    id: 'cnm010',
    slug: 'adesivo-cnm-oficial',
    sku: 'ADH001',
    name: 'Adesivo CNM Oficial',
    price: 15.00,
    image: '/images/adesivo-01.jpg',
    color: '',
    category: 'adesivos',
    stock: 50,
  },
];

export const getFeatured = () => products.filter(p => p.category === 'bones').slice(0, 6);
export const getBySlug   = (slug: string) => products.find(p => p.slug === slug);
export const getByCategory = (cat: string) => products.filter(p => p.category === cat);
